[tool.pyright]

include = [
    "video",
    "server",
    "setup"
]
exclude = [
    "**/__pycache__"
]
venvPath = "."
venv = ".venv"
pythonPlatform = "Linux"

reportOptionalMemberAccess = "none"

[tool.ruff]

fix = true
respect-gitignore = true
line-length = 88
indent-width = 2
target-version = "py312"
src = ["video", "server", "setup"]

[tool.lint]

ignore = ["E501"]

[tool.ruff.format]

indent-style = "space"
line-ending = "lf"
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 60

[tool.ruff.lint.flake8-quotes]

docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.pycodestyle]

max-doc-length = 88
max-line-length = 88
ignore-overlong-task-comments = false

[tool.ruff.lint.pydocstyle]

convention = "google"

[tool.mypy]

strict = false
allow_redefinition = true

disable_error_code = [
  "call-overload",
  "import-untyped"
]
